--liquibase formatted sql

--changeset crowdynamics:1
CREATE TABLE DEVICES(
ID BIGSERIAL, 
DEVICE_ID VARCHAR(6) NOT NULL,
USER_ID NUMERIC(6) NULL,
MODEL_NAME VARCHAR(20) NOT NULL,
DESCRIPTION VARCHAR(150)  NULL,
PRIMARY KEY (ID)
);
--rollback DROP TABLE DEVICES;